basic_experiment:
  batch_size: 64
  memory_dataset: false
  n_epochs: 100
  output_folder: eir_tutorials/tutorial_runs/i_scaling/02_scaling_compute
  valid_size: 1024
  dataloader_workers: 0
optimization:
  lr: 0.0006
  wd: 0.1
evaluation_checkpoint:
  checkpoint_interval: 1000
  n_saved_models: 1
  sample_interval: 1000
data_preparation:
  streaming_setup_samples: 2048
model:
  compile_model: true
accelerator:
  devices: auto
  hardware: auto
  num_nodes: 1
  precision: bf16-mixed
  strategy: auto
visualization_logging:
  plot_skip_steps: 5000