basic_experiment:
  batch_size: 128
  memory_dataset: false
  n_epochs: 100
  output_folder: eir_tutorials/tutorial_runs/i_scaling/02_scaling_compute
  valid_size: 500
  dataloader_workers: 8
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
data_preparation:
  streaming_setup_samples: 100000
model:
  compile_model: true
accelerator:
  precision: bf16
