attribution_analysis:
  attributions_every_sample_factor: 3
  compute_attributions: true
  max_attributions_per_class: 512
basic_experiment:
  batch_size: 32
  memory_dataset: true
  n_epochs: 500
  output_folder: eir_tutorials/tutorial_runs/a_using_eir/tutorial_03_anti_breast_cancer_peptides_run
  valid_size: 0.25
evaluation_checkpoint:
  checkpoint_interval: 200
  n_saved_models: 1
  sample_interval: 200
training_control:
  early_stopping_buffer: 2000
  weighted_sampling_columns:
  - all
