basic_experiment:
  batch_size: 64
  memory_dataset: false
  n_epochs: 3
  output_folder: eir_tutorials/tutorial_runs/c_sequence_output/03_image_captioning
  valid_size: 500
  dataloader_workers: 8
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
optimization:
  lr: 0.001
  optimizer: adabelief
