attribution_analysis:
  compute_attributions: true
  max_attributions_per_class: 10
basic_experiment:
  batch_size: 32
  dataloader_workers: 0
  memory_dataset: true
  n_epochs: 200
  output_folder: eir_tutorials/tutorial_runs/a_using_eir/tutorial_05_is_it_a_hot_dog
  valid_size: 0.1
evaluation_checkpoint:
  checkpoint_interval: 100
  n_saved_models: 1
  sample_interval: 100
training_control:
  mixing_alpha: 0.5
visualization_logging:
  plot_skip_steps: 0
