basic_experiment:
  batch_size: 128
  memory_dataset: false
  n_epochs: 20
  output_folder: eir_tutorials/tutorial_runs/g_time_series/02_time_series_stocks_one_shot
  valid_size: 2000
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
optimization:
  lr: 0.0005
  optimizer: adabelief
visualization_logging:
  plot_skip_steps: 2000
data_preparation:
  streaming_setup_samples: 20000
