basic_experiment:
  batch_size: 256
  memory_dataset: false
  n_epochs: 20
  output_folder: eir_tutorials/tutorial_runs/c_sequence_output/04_protein_sequences
  valid_size: 512
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
latent_sampling:
  layers_to_sample:
  - output_modules.protein_sequence.output_transformer.layers.1
optimization:
  lr: 0.001
  optimizer: adabelief
