output_folder: eir_tutorials/tutorial_runs/f_image_output/01_image_foundation
valid_size: 1024
n_saved_models: 1
checkpoint_interval: 500
plot_skip_steps: 200
sample_interval: 500
memory_dataset: false
dataloader_workers: 8
n_epochs: 20
batch_size: 64
lr: 0.0005
lr_plateau_patience: 6
optimizer: "adabelief"
device: "mps"