basic_experiment:
  batch_size: 256
  memory_dataset: true
  n_epochs: 10
  output_folder: eir_tutorials/tutorial_runs/c_sequence_output/02_seq_to_seq
  valid_size: 500
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
optimization:
  lr: 0.001
  optimizer: adabelief