basic_experiment:
  batch_size: 64
  dataloader_workers: 8
  device: mps
  memory_dataset: false
  n_epochs: 5
  output_folder: eir_tutorials/tutorial_runs/f_image_output/01_image_foundation
  valid_size: 1024
evaluation_checkpoint:
  checkpoint_interval: 500
  n_saved_models: 1
  sample_interval: 500
lr_schedule:
  lr_schedule: cosine
optimization:
  lr: 0.0003
  optimizer: adamw
visualization_logging:
  plot_skip_steps: 200
